# example netlify.toml
[build]
#   command = "npm install && cd ./qwerty-hancock && npm link && cd .. && npm link qwerty-hancock && npm run build"
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200